In [23]:
import socket
ip_port = ('35.193.237.218',38471)
# ip_port = ('127.0.0.1',38472)
sk = socket.socket()
sk.connect(ip_port)
print ("客户端启动:")

origin = '40.658,-73.987'
destination = '40.807,-73.964'
inp = origin + '|' + destination
sk.sendall(inp)
server_response=sk.recv(1024)
print (server_response)
sk.close()

客户端启动:
43.8|51.13


In [18]:
origin = '40.758,-73.987'
destination = '40.807, -73.964'
inp = origin + '|' + destination

In [4]:
type(inp)

str

In [47]:
import socketserver
import json
from sklearn.externals import joblib
import simplejson
import urllib
import datetime
import numpy as np

client_data = inp
origin = client_data.split('|')[0]
destination = client_data.split('|')[1]
url = "http://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=%s&destinations=%s&sensor=false&mode=driving"%(origin,destination)
result= simplejson.load(urllib.urlopen(url))
duration = result['rows'][0]['elements'][0]['duration']['value']
trip_distance = result['rows'][0]['elements'][0]['distance']['text']

data = (float(trip_distance[:-3]), float(duration))
weather_forecast = json.load(open('weather_forecast.json'))
hour = datetime.datetime.now().strftime('%H')
weather = weather_forecast[hour][1:]
data = data + (weather[0],weather[2],weather[3])
vec = joblib.load('12_vec.pkl')
dummyX = vec.transform([{'Weather':weather[1]}]).toarray()
data = np.hstack([np.array(data),dummyX[0]])
print data


[  4.80000000e+00   1.31600000e+03   5.30000000e+01   8.00000000e+00
   0.00000000e+00   1.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00]


In [37]:
dummyX

array([[ 1.,  0.,  0.,  0.,  0.,  0.]])

In [39]:
np.array(data)

array([    4.8,  1316. ,    53. ,     8. ,     0. ])

In [45]:
np.hstack([np.array(data),dummyX[0]])

array([  4.80000000e+00,   1.31600000e+03,   5.30000000e+01,
         8.00000000e+00,   0.00000000e+00,   1.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00])